steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '18'
  - name: Cypress run
    uses: cypress-io/github-action@v2
    continue-on-error: true
    with:
      install-command: npm install
      browser: chrome
  - name: Publish Report
    uses: peaceiris/actions-gh-pages@v3
    with:
      deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      publish_dir: ./mochawesome-report
