name: EBAC CI

on:
  push:
    branches: [ci]
    
  workflow_dispatch:
  
jobs:

  cypress:
    
    runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Executar Cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome
      - name: Publicar Relatório
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./mochawesome-report
